title: My self
description: >-
  My name is Avinash I am very talented boy and I love to sing song and eating
  banana and I love sara very much she is my crush
template:
  repo: my-self-template
  name: my-self
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
